version: "3.9"
services:
  node:
    image: "node:18-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=3000
    command: sh -c "yarn install && yarn run start"
    stdin_open: true
    tty: true

networks:
  dendrofen_react_chakra_network:
    external: true